<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
          'subject' => 'required|min:5|max:100',
          'name' => 'required|min:3',
          'message' => 'required|min:5|max:1000',
        ];
    }

    public function attributes()
    {
      return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function messages()
    {
      return [
        'name.require' => 'Поле имя является обязательным.',
        'name.min' => 'Поле имя должно быть не менее 3 символов.'
      ];
    }
}
