<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class OrderRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'product_id' => ['required', 'integer', 'exists:products,id'],
            'uid' => ['required', 'string', 'min:5', 'max:14', 'regex:/^5\d{4,13}$/'],
            // client_id deprecated - removed for security
        ];
    }

    public function attributes()
    {
      return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function messages()
    {
        return [
            'product_id.required' => 'Поле product_id является обязательным.',
            'product_id.exists' => 'Выбранный продукт не существует.',
            'uid.required' => 'Player ID является обязательным.',
            'uid.regex' => 'Player ID должен начинаться с 5 и содержать 5-14 цифр.',
            'uid.min' => 'Player ID слишком короткий (минимум 5 цифр).',
            'uid.max' => 'Player ID слишком длинный (максимум 14 цифр).',
        ];
    }
}
